---
version: 0.2

phases:
  install:
    commands:
      - npm install --silent --progress=false -g npm
      - npm install --silent --progress=false -g serverless
      - npm install --silent --progress=false
      - npm --version
  build:
    commands:
      - npm run-script lint
      - npm test
  post_build:
    commands:
      - serverless deploy --stage dev
...