---
version: 0.2

phases:
  install:
    commands:
      - npm install -g npm
      - npm install -g serverless
      - npm install
      - npm --version
  build:
    commands:
      - npm run-script lint
      - npm test
  post_build:
    commands:
      - serverless deploy --stage dev
...